export const FETCH_KEYWORDS = 'FETCH_KEYWORDS';
export const FETCH_KEYWORDS_ERROR = 'FETCH_KEYWORDS_ERROR';
export const ADD_KEYWORDS = 'ADD_KEYWORDS';
export const ADD_KEYWORDS_ERROR = 'ADD_KEYWORDS_ERROR'
export const REMOVE_KEYWORDS = 'REMOVE_KEYWORDS';
export const REMOVE_KEYWORDS_ERROR = 'REMOVE_KEYWORDS_ERROR';
